# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Build
    before: cd react-app
    init: yarn # runs during prebuild
  - name: Run
    command: cd react-app && npx craco start

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
