# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Build & Run
    before: cd react-app
    init: yarn # runs during prebuild
    command: npx craco start

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true