image: node:lts

# react-app deployment
pages:
  stage: deploy
  before_script:
    - cd react-app
  script:
    - npm install
    - npm run build-ci
    - rm -rf ../public
    - mv build ../public
  artifacts:
    paths:
      - public
  only:
    - master